import { QuestionsThematique } from '../Referentiel';

export const donneesSecuriteInfrastructureEnglish: QuestionsThematique = {
  questions: [
    {
      identifiant: 'securite-infrastructure-pare-feu-deploye',
      libelle: 'Is the internet connection protected by a firewall?',
      poids: 1,
      reponsesPossibles: [
        {
          identifiant: 'securite-infrastructure-pare-feu-deploye-nsp',
          libelle: 'I do not know',
          ordre: 0,
        },
        {
          identifiant: 'securite-infrastructure-pare-feu-deploye-non',
          libelle: 'No',
          resultat: {
            indice: { valeur: 0 },
            mesures: [
              {
                identifiant: 'securite-infrastructure-pare-feu-deploye',
                niveau: 1, 
                categorie: "technique",
              },
            ],
          },
          ordre: 1,
        },
        {
          identifiant: 'securite-infrastructure-pare-feu-deploye-oui',
          libelle: 'Yes',
          questions: [
            {
              identifiant:
                'securite-infrastructure-pare-feu-deploye-oui-tiroir-interconnexions-protegees',
              libelle:
                'Are only strictly necessary inbound and outbound traffic allowed between the internet and the information system (or other external networks)?',
              poids: 2,
              reponsesPossibles: [
                {
                  identifiant:
                    'securite-infrastructure-pare-feu-deploye-oui-tiroir-interconnexions-protegees-nsp',
                  libelle: 'I do not know',
                  ordre: 0,
                },
                {
                  identifiant:
                    'securite-infrastructure-pare-feu-deploye-oui-tiroir-interconnexions-protegees-non',
                  libelle: 'No',
                  resultat: {
                    indice: { valeur: 0 },
                    mesures: [
                      {
                        identifiant:
                          'securite-infrastructure-pare-feu-deploye-interconnexions-protegees',
                        niveau: 1, 
                        categorie: "technique",
                      },
                    ],
                  },
                  ordre: 1,
                },
                {
                  identifiant:
                    'securite-infrastructure-pare-feu-deploye-oui-tiroir-interconnexions-protegees-oui',
                  libelle: 'Yes',
                  resultat: {
                    indice: { valeur: 2 },
                    mesures: [
                      {
                        identifiant:
                          'securite-infrastructure-pare-feu-deploye-interconnexions-protegees',
                        niveau: 2, 
                        categorie: "technique",
                      },
                    ],
                  },
                  ordre: 2,
                },
                {
                  identifiant:
                    'securite-infrastructure-pare-feu-deploye-oui-tiroir-interconnexions-protegees-oui-VPN',
                  libelle: 'Yes, and inbound traffic is protected by a VPN',
                  resultat: {
                    indice: { valeur: 3 },
                  },
                  ordre: 3,
                },
              ],
              type: 'choixUnique',
            },
            {
              identifiant:
                'securite-infrastructure-pare-feu-deploye-oui-tiroir-logs-stockes',
              libelle:
                'Are traffic logs (generated by the firewall) for inbound, outbound, and blocked traffic stored?',
              poids: 2,
              reponsesPossibles: [
                {
                  identifiant:
                    'securite-infrastructure-pare-feu-deploye-oui-tiroir-logs-stockes-nsp',
                  libelle: 'I do not know',
                  ordre: 0,
                },
                {
                  identifiant:
                    'securite-infrastructure-pare-feu-deploye-oui-tiroir-logs-stockes-non',
                  libelle: 'No',
                  resultat: {
                    indice: { valeur: 0 },
                    mesures: [
                      {
                        identifiant:
                          'securite-infrastructure-pare-feu-deploye-logs-stockes',
                        niveau: 1, 
                        categorie: "technique",
                      },
                    ],
                  },
                  ordre: 1,
                },
                {
                  identifiant:
                    'securite-infrastructure-pare-feu-deploye-oui-tiroir-logs-stockes-oui-logs-stockes',
                  libelle: 'Yes, we store some firewall logs',
                  resultat: {
                    indice: { valeur: 1 },
                    mesures: [
                      {
                        identifiant:
                          'securite-infrastructure-pare-feu-deploye-logs-stockes',
                        niveau: 1, 
                        categorie: "technique",
                      },
                    ],
                  },
                  ordre: 2,
                },
                {
                  identifiant:
                    'securite-infrastructure-pare-feu-deploye-oui-tiroir-logs-stockes-oui-logs-stockes-conserves-6-mois',
                  libelle:
                    'Yes, we store firewall logs with a retention period of at least 6 months',
                  resultat: { indice: { valeur: 3 } },
                  ordre: 2,
                },
              ],
              type: 'choixUnique',
            },
          ],
          ordre: 2,
        },
      ],
      type: 'choixUnique',
    },
    {
      identifiant: 'securite-infrastructure-si-industriel-pare-feu-deploye',
      libelle:
        'Have specific network segmentation measures been implemented for industrial control systems?',
      poids: 2,
      reponsesPossibles: [
        {
          identifiant:
            'securite-infrastructure-si-industriel-pare-feu-deploye-na',
          libelle: 'Not applicable',
          ordre: 0,
        },
        {
          identifiant:
            'securite-infrastructure-si-industriel-pare-feu-deploye-nsp',
          libelle: 'I do not know',
          ordre: 1,
        },
        {
          identifiant:
            'securite-infrastructure-si-industriel-pare-feu-deploye-non',
          libelle: 'No',
          resultat: {
            indice: { valeur: 0 },
            mesures: [
              {
                identifiant:
                  'securite-infrastructure-si-industriel-pare-feu-deploye',
                niveau: 1, 
                categorie: "technique",
              },
            ],
          },
          ordre: 2,
        },
        {
          identifiant:
            'securite-infrastructure-si-industriel-pare-feu-deploye-oui-flux-necessaires-bloques',
          libelle: 'Yes, all unnecessary network traffic is blocked',
          resultat: {
            indice: { valeur: 1.5 },
            mesures: [
              {
                identifiant:
                  'securite-infrastructure-si-industriel-pare-feu-deploye',
                niveau: 2, 
                categorie: "technique",
              },
            ],
          },
          ordre: 3,
        },
        {
          identifiant:
            'securite-infrastructure-si-industriel-pare-feu-deploye-oui-segmentation-stricte',
          libelle:
            'Yes, strict network segmentation has been implemented to isolate the industrial environment from the corporate environment (except for justified business needs)',
          resultat: { indice: { valeur: 3 } },
          ordre: 4,
        },
      ],
      type: 'choixUnique',
    },
    {
      identifiant:
        'securite-infrastructure-mises-a-jour-fonctionnelles-securite-equipements-securite-deployees',
      libelle:
        'Are functional and security updates deployed for security equipment?',
      poids: 3,
      reponsesPossibles: [
        {
          identifiant:
            'securite-infrastructure-mises-a-jour-fonctionnelles-securite-equipements-securite-deployee-na',
          libelle: 'Not applicable',
          ordre: 0,
        },
        {
          identifiant:
            'securite-infrastructure-mises-a-jour-fonctionnelles-securite-equipements-securite-deployees-nsp',
          libelle: 'I do not know',
          ordre: 1,
        },
        {
          identifiant:
            'securite-infrastructure-mises-a-jour-fonctionnelles-securite-equipements-securite-deployees-non',
          libelle: 'No',
          resultat: {
            indice: { valeur: 0 },
            mesures: [
              {
                identifiant:
                  'securite-infrastructure-mises-a-jour-fonctionnelles-securite-equipements-securite-deployees',
                niveau: 1, 
                categorie: "technique",
              },
            ],
          },
          ordre: 2,
        },
        {
          identifiant:
            'securite-infrastructure-mises-a-jour-fonctionnelles-securite-equipements-securite-deployees-des-que-possible',
          libelle:
            'All software updates are deployed as soon as they are available and functional',
          resultat: { indice: { valeur: 3 } },
          ordre: 3,
        },
      ],
      type: 'choixUnique',
    },
    {
      identifiant:
        'securite-infrastructure-mises-a-jour-fonctionnelles-securite-systemes-exploitation-securite-deployees',
      libelle:
        'Are functional and security updates deployed for operating systems of servers, services, and administration software?',
      poids: 3,
      reponsesPossibles: [
        {
          identifiant:
            'securite-infrastructure-mises-a-jour-fonctionnelles-securite-systemes-exploitation-securite-deployees-na',
          libelle: 'Not applicable',
          ordre: 0,
        },
        {
          identifiant:
            'securite-infrastructure-mises-a-jour-fonctionnelles-securite-systemes-exploitation-securite-deployees-nsp',
          libelle: 'I do not know',
          ordre: 1,
        },
        {
          identifiant:
            'securite-infrastructure-mises-a-jour-fonctionnelles-securite-systemes-exploitation-securite-deployees-non',
          libelle: 'No',
          resultat: {
            indice: { valeur: 0 },
            mesures: [
              {
                identifiant:
                  'securite-infrastructure-mises-a-jour-fonctionnelles-securite-systemes-exploitation-securite-deployees',
                niveau: 1, 
                categorie: "technique",
              },
            ],
          },
          ordre: 2,
        },
        {
          identifiant:
            'securite-infrastructure-mises-a-jour-fonctionnelles-securite-systemes-exploitation-securite-deployees-a-intervalle-regulier',
          libelle:
            'Updates are systematically deployed, though some exceptions currently remain unaddressed',
          resultat: {
            indice: { valeur: 1.5 },
            mesures: [
              {
                identifiant:
                  'securite-infrastructure-mises-a-jour-fonctionnelles-securite-systemes-exploitation-securite-deployees',
                niveau: 2, 
                categorie: "technique",
              },
            ],
          },
          ordre: 3,
        },
        {
          identifiant:
            'securite-infrastructure-mises-a-jour-fonctionnelles-securite-systemes-exploitation-securite-deployees-des-que-possible',
          libelle:
            'All updates are systematically deployed as soon as they are available, and exceptions are subject to additional compensatory measures',
          resultat: { indice: { valeur: 3 } },
          ordre: 4,
        },
      ],
      type: 'choixUnique',
    },
    {
      identifiant:
        'securite-infrastructure-outils-securisation-systeme-messagerie',
      libelle:
        'Are specific measures and tools implemented to secure the email system?',
      poids: 1,
      reponsesPossibles: [
        {
          identifiant:
            'securite-infrastructure-outils-securisation-systeme-messagerie-na',
          libelle: 'Not applicable',
          ordre: 0,
        },
        {
          identifiant:
            'securite-infrastructure-outils-securisation-systeme-messagerie-nsp',
          libelle: 'I do not know',
          ordre: 1,
        },
        {
          identifiant:
            'securite-infrastructure-outils-securisation-systeme-messagerie-non',
          libelle: 'No',
          resultat: {
            indice: { valeur: 0 },
            mesures: [
              {
                identifiant:
                  'securite-infrastructure-outils-securisation-systeme-messagerie',
                niveau: 1, 
                categorie: "technique",
              },
            ],
          },
          ordre: 2,
        },
        {
          identifiant:
            'securite-infrastructure-outils-securisation-systeme-messagerie-antispam',
          libelle:
            'Yes, anti-spam and anti-phishing tools have been implemented',
          resultat: {
            indice: { valeur: 2 },
            mesures: [
              {
                identifiant:
                  'securite-infrastructure-outils-securisation-systeme-messagerie',
                niveau: 2, 
                categorie: "technique",
              },
            ],
          },
          ordre: 3,
        },
        {
          identifiant:
            'securite-infrastructure-outils-securisation-systeme-messagerie-webmail',
          libelle:
            'Yes, anti-spam and anti-phishing tools have been implemented, and additional protection mechanisms against illegitimate emails are enabled',
          resultat: { indice: { valeur: 3 } },
          ordre: 4,
        },
      ],
      type: 'choixUnique',
    },
    {
      identifiant: 'securite-infrastructure-acces-wifi-securises',
      libelle: 'Are Wi-Fi access points secured?',
      poids: 1,
      reponsesPossibles: [
        {
          identifiant: 'securite-infrastructure-acces-wifi-securises-na',
          libelle: 'Not applicable',
          ordre: 0,
        },
        {
          identifiant: 'securite-infrastructure-acces-wifi-securises-nsp',
          libelle: 'I do not know',
          ordre: 1,
        },
        {
          identifiant: 'securite-infrastructure-acces-wifi-securises-non',
          libelle: 'No',
          resultat: {
            indice: { valeur: 0 },
            mesures: [
              {
                identifiant: 'securite-infrastructure-acces-wifi-securises',
                niveau: 1, 
                categorie: "technique",
              },
            ],
          },
          ordre: 2,
        },
        {
          identifiant:
            'securite-infrastructure-acces-wifi-securises-oui-chiffrement-robuste',
          libelle: 'Yes, Wi-Fi connection encryption is robust',
          resultat: {
            indice: { valeur: 2 },
            mesures: [
              {
                identifiant: 'securite-infrastructure-acces-wifi-securises',
                niveau: 2, 
                categorie: "technique",
              },
            ],
          },
          ordre: 3,
        },
        {
          identifiant:
            'securite-infrastructure-acces-wifi-securises-oui-chiffrement-robuste-acces-visiteur-restreint',
          libelle:
            'Yes, Wi-Fi connection encryption is robust and guests do not have access to the internal network',
          resultat: { indice: { valeur: 3 } },
          ordre: 4,
        },
      ],
      type: 'choixUnique',
    },
    {
      identifiant: 'securite-infrastructure-espace-stockage-serveurs',
      libelle:
        'Is access to the room or space dedicated to storing administration servers, IT racks, and network equipment protected by a secure door?',
      poids: 1,
      reponsesPossibles: [
        {
          identifiant: 'securite-infrastructure-espace-stockage-serveurs-na',
          libelle: 'Not applicable',
          ordre: 0,
        },
        {
          identifiant: 'securite-infrastructure-espace-stockage-serveurs-nsp',
          libelle: 'I do not know',
          ordre: 1,
        },
        {
          identifiant: 'securite-infrastructure-espace-stockage-serveurs-non',
          libelle: 'No',
          resultat: {
            indice: { valeur: 0 },
            mesures: [
              {
                identifiant: 'securite-infrastructure-espace-stockage-serveurs',
                niveau: 1, 
                categorie: "technique",
              },
            ],
          },
          ordre: 2,
        },
        {
          identifiant:
            'securite-infrastructure-espace-stockage-serveurs-oui-porte-ferme-a-clef',
          libelle: 'Yes, access is restricted only to authorized personnel',
          resultat: {
            indice: { valeur: 1.5 },
            mesures: [
              {
                identifiant: 'securite-infrastructure-espace-stockage-serveurs',
                niveau: 2, 
                categorie: "technique",
              },
            ],
          },
          ordre: 3,
        },
        {
          identifiant:
            'securite-infrastructure-espace-stockage-serveurs-oui-porte-ferme-a-clef-videosurveillance',
          libelle:
            'Yes, access is restricted only to authorized personnel and is monitored by a video surveillance system',
          resultat: { indice: { valeur: 3 } },
          ordre: 4,
        },
      ],
      type: 'choixUnique',
    },
  ],
};